
ACCOUNTS = [
  "GBRPULFLBPFCDZS7LYRYS7IUTHZYH6PCRK2EL7MIJBQGRBKW5JVRE3IN",
  "GDJ5G3LUE4SRSDAJ24FFAUK6ODNDPQX2YRJGBZGTZM5QQUG2KL3KXYTU",
  "GBFDIJMM3Q3WGVYFMNVI3MAC5VJXT37CILVVDYFKKHFCXQP4NIWPYIMW"
]
  
[[CURRENCIES]]
code="FighterIndex"
issuer="GBRPULFLBPFCDZS7LYRYS7IUTHZYH6PCRK2EL7MIJBQGRBKW5JVRE3IN"
display_decimals=7
name="FighterIndex"
desc="The FighterIndex token is an upcoming Marketplace for the Fight Industry!"
image="https://fighterindex.com/assets/img/FighterIndex.png"
status="live"

[[PRINCIPALS]]
name="FighterIndex"
email="FighterIndex@gmail.com"
telegram="https://t.me/FighterIndex"
twitter="https://twitter.com/FighterIndex"
github="https://github.com/FighterIndex"
